EasyCash.PresentationLayer/Controllers/SendMoneyController.cs
using EasyCash.BusinessLayer.Abstract;
using EasyCash.DataAccessLayer.Concrete;
using EasyCash.DtoLayer.Dtos.CustomerAccountProcessDTOs;
using EasyCash.EntityLayer.Concrete;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EasyCash.PresentationLayer.Controllers
{
    public class SendMoneyController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly ICustomerAccountProcessService _customerAccountProcessService;

        public SendMoneyController(UserManager<AppUser> userManager, ICustomerAccountProcessService customerAccountProcessService)
        {
            _userManager = userManager;
            _customerAccountProcessService = customerAccountProcessService;
        }

        [HttpGet]
        public IActionResult Index(string myCurrency)
        {
            ViewBag.Currency = myCurrency;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index(SendMoneyForCustomerAccountProcessDto model)
        {
            var context = new Context();
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var receiverAccountNumberID = context.CustomerAccounts.Where(x => x.CustomerAccountNumber == model.ReceiverAccountNumber).Select(y => y.CustomerAccountID).FirstOrDefault();

            var senderAccountNumberID = context.CustomerAccounts.Where(x => x.AppUserId == user.Id).Where(y => y.CustomerAccountCurrency == "TL").Select(z => z.CustomerAccountID).FirstOrDefault();

            var values = new CustomerAccountProcess()
            {
                ProcessDate = Convert.ToDateTime(DateTime.Now.ToShortDateString()),
                SenderID = senderAccountNumberID,
                ProcessType = "Havale",
                ReceiverID = receiverAccountNumberID,
                Amount = model.Amount,
                Description = model.Description
            };

            _customerAccountProcessService.TInsert(values);

            return RedirectToAction("Index", "Deneme");
        }
    }
}

EasyCash.PresentationLayer/Views/Shared/Components/_CustomerLayoutSidebarPartial/Default.cshtml
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Easy Cash</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="~/gentela-gh-pages/production/images/img.jpg" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>Musteri X</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>Menus</h3>
                <ul class="nav side-menu">
                    <li>
                        <a><i class="fa fa-home"></i> Home Pages <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="index.html">Dashboard</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-edit"></i> Account Transactions <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="form.html">Money Transfer</a></li>
                            <li><a href="form_advanced.html">Recent Transactions</a></li>
                            <li><a href="form_validation.html">Send Money By QR </a></li>
                            <li><a href="form_wizards.html">Share IBAN</a></li>
                            <li><a href="form_upload.html">Transfer Within My Accounts</a></li>
                            <li><a href="form_buttons.html">Remittance to Mobile</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-desktop"></i> My Accounts <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="general_elements.html">All Acounts</a></li>
                            <li><a href="media_gallery.html">New Account</a></li>
                            <li><a href="typography.html">Checking Accounts</a></li>
                            <li><a href="icons.html">Future Accounts</a></li>
                            <li><a href="glyphicons.html">Gold Accounts</a></li>
                            <li><a href="widgets.html">Credit Accounts</a></li>
                            <li><a href="invoice.html">USD Accounts</a></li>
                            <li><a href="inbox.html">EUR Accounts</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-car"></i> Transfers <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a asp-controller="SendMoney" asp-action="Index" asp-route-myCurrency = "TL">Turkish Lira Transfers</a></li>
                            <li><a asp-controller="SendMoney" asp-action="Index" asp-route-myCurrency="USD">Dollar Transfers</a></li>
                            <li><a asp-controller="SendMoney" asp-action="Index" asp-route-myCurrency="EUR">Euro Transfers</a></li>
                            <li><a asp-controller="SendMoney" asp-action="Index" asp-route-myCurrency="Other">Other Transfers</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-table"></i> Payments <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="tables.html">Bill Payments</a></li>
                            <li><a href="tables_dynamic.html">Education Payments</a></li>
                            <li><a href="tables_dynamic.html">Trafic Payments</a></li>
                            <li><a href="tables_dynamic.html">Exam Payments</a></li>
                            <li><a href="tables_dynamic.html">Insurance Payments</a></li>
                            <li><a href="tables_dynamic.html">Other Payments</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-bar-chart-o"></i> Currency And Gold <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="chartjs.html">Exchanges</a></li>
                            <li><a href="chartjs2.html">Currency Transactions</a></li>
                            <li><a href="morisjs.html">Gold Transactions</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-clone"></i>Loans <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="fixed_sidebar.html">Loan Accounts</a></li>
                            <li><a href="fixed_footer.html">Loan Requests</a></li>
                            <li><a href="fixed_footer.html">Loan Payments</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="menu_section">
                <h3>Live On</h3>
                <ul class="nav side-menu">
                    <li>
                        <a><i class="fa fa-bug"></i> My Cards <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="e_commerce.html">Credit Cards</a></li>
                            <li><a href="projects.html">Debit Cards</a></li>
                            <li><a href="project_detail.html">Virtual Cards</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-windows"></i> Settings <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="page_403.html">Change Password</a></li>
                            <li><a href="page_404.html">Profile</a></li>
                            <li><a href="page_500.html">Contact</a></li>
                        </ul>
                    </li>
                    <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Logout </a></li>
                </ul>
            </div>

        </div>
        <!-- /sidebar menu -->
        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>